version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - RODA_LOG_LEVEL=warn
      - DATABASE_URL=extralite://storage/production.sqlite
    volumes:
      - storage:/roda/storage

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"

volumes:
  storage:
  sockets:
