version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - WEB_CONCURRENCY=0
      - RODA_MAX_THREADS=5
      - RODA_LOG_LEVEL=warn
      - DATABASE_URL=extralite://storage/production.sqlite
    volumes:
      - storage:/roda/storage
      - sockets:/roda/tmp/sockets
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "250MB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/roda/tmp/sockets
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

volumes:
  storage:
  sockets:
